-- *created_at default
ALTER TABLE nora.schedules ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE nora.categories MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE nora.users MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE nora.repeat_rules MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- importance 범위 제한 (1~5)
ALTER TABLE nora.schedules MODIFY COLUMN importance INT CHECK (importance BETWEEN 1 AND 5);